api.info:
  title: Iorek
  description: Iorek
  version: v1
  termsOfService: tosUrl
  contact:
    name: Stuart Beard
    email: stuart@stuartbeard.com
    url: https://www.stuartbeard.com
  licenseTitle: licenseTitle
  licenseUrl: licenseUrl

breach.service:
  name: "hibp"
  url:
    pp: "https://api.pwnedpasswords.com"
    hibp: "https://haveibeenpwned.com/api/v2"
  prefix.length: 5

credential.safety:
  ok:
    message: "Your password did not appear in any known data breach."
    threshold: 0
  warning:
    message: "Your password appeared %s times in known breached data. You can use this password, but you probably shouldn't."
    threshold: 0
  severe:
    message: "Your password appeared %s times in known breached data. As this represents a severe risk, you may not use this password."
    threshold: 1000
  preventSevere: true
