breach.service:
  name: "hibp"
  url:
    pp: "https://api.pwnedpasswords.com"
    hibp: "https://haveibeenpwned.com/api/v2"
  prefix.length: 5

credential.safety:
  ok:
    message: "The input password did not appear in any known breach within the data set."
    threshold: 0
  warning:
    message: "The input password appeared %s times in the breach data set. You can use this password, but you probably shouldn't."
    threshold: 0
  severe:
    message: "The input password appeared %s times in the breach data set. As this represents a severe risk, you may not use this password."
    threshold: 1000
  preventSevere: true
